/**
 * createSlideTool
 *
 * Creates a NEW slide from scratch based on a detailed prompt
 *
 * Use cases:
 * - Generate individual slides for a deck
 * - Create slides with specific content
 * - Apply brand themes and logos
 * - Include custom images in slides
 *
 * @tool
 */

import { GoogleGenAI } from '@google/genai';
import type { ToolResult, CreateSlideParams, CreateSlideResult, BrandTheme } from '../types';

const ai = new GoogleGenAI({ apiKey: process.env.VITE_GEMINI_API_KEY || '' });

/**
 * Helper: Convert base64 data URL to GenerativePart
 */
function fileToGenerativePart(base64Data: string) {
  const match = base64Data.match(/^data:(image\/\w+);base64,(.*)$/);
  if (!match) {
    throw new Error('Invalid base64 image data string');
  }
  return {
    inlineData: {
      data: match[2],
      mimeType: match[1],
    },
  };
}

/**
 * Helper: Generate single image variation using Gemini Flash Image
 */
async function generateSingleImage(
  model: string,
  imageParts: any[],
  prompt: string,
  deepMode: boolean
): Promise<{ image: string; finalPrompt: string }> {
  const parts = [...imageParts, { text: prompt }];

  const response = await ai.models.generateContent({
    model,
    contents: [{ role: 'user', parts }],
    config: {
      thinking: deepMode
        ? { mode: 'deep', instruction: 'Think deeply about visual design principles, layout, and aesthetics' }
        : undefined,
    },
  });

  // Find the image part (could be in parts[0] or parts[1] depending on input)
  const parts = response?.candidates?.[0]?.content?.parts || [];
  let base64ImageBytes: string | undefined;
  let mimeType = 'image/png';

  for (const part of parts) {
    if (part.inlineData?.data) {
      base64ImageBytes = part.inlineData.data;
      mimeType = part.inlineData.mimeType || 'image/png';
      break;
    }
  }

  if (!base64ImageBytes) {
    console.error('[generateSingleImage] No image found in response parts');
    throw new Error('No image was generated by Gemini (Reason: NO_IMAGE)');
  }

  return {
    image: `data:${mimeType};base64,${base64ImageBytes}`,
    finalPrompt: prompt,
  };
}

/**
 * Creates a new slide from a detailed prompt
 * Wraps the tested createSlideFromPrompt logic from services/geminiService.ts
 */
export async function createSlide(params: CreateSlideParams): Promise<ToolResult<CreateSlideResult>> {
  const startTime = Date.now();

  try {
    console.log(`[createSlideTool] Creating slide with prompt length: ${params.detailedPrompt.length}`);
    console.log(`[createSlideTool] Reference: ${params.referenceSlideImage ? 'YES' : 'NO'}`);
    console.log(`[createSlideTool] Theme: ${params.theme ? 'YES' : 'NO'}`);
    console.log(`[createSlideTool] Logo: ${params.logoImage ? 'YES' : 'NO'}`);
    console.log(`[createSlideTool] Custom Image: ${params.customImage ? 'YES' : 'NO'}`);
    console.log(`[createSlideTool] Deep Mode: ${params.deepMode}`);

    // Build theme instructions
    let themeInstructions = '';
    if (params.theme) {
      themeInstructions = `

**THEME INSTRUCTIONS:**
- Primary Color: ${params.theme.primaryColor}
- Secondary Color: ${params.theme.secondaryColor}
- Accent Color: ${params.theme.accentColor}
- Font Style: ${params.theme.fontStyle}
- Visual Style: ${params.theme.visualStyle}`;
    }

    // Build logo instructions
    let logoInstructions = '';
    if (params.logoImage) {
      logoInstructions = `

**LOGO PLACEMENT INSTRUCTION:** A company logo has been provided as a reference image.

**CRITICAL: PRESERVE EXISTING LOGOS**
- If the original slide already contains logos (e.g., Google Cloud, AWS, Microsoft, etc.), you MUST keep them exactly as they are
- The new logo should be ADDED to the slide, not replace existing logos
- If there's already a logo in the top-right corner, place the new logo in a different position (top-left, bottom-right, or bottom-left)
- If the top-right is empty, place the new logo there

**Logo Specifications:**
- Position: Top-right corner preferred (if available), otherwise top-left or bottom corner
- Size: Approximately 120-180px width (scale proportionally to match existing logos)
- Padding: 40-60px from edges
- Style: Recreate the logo's colors, shapes, and design elements as faithfully as possible
- Background: Ensure the logo has proper contrast against the slide background
- Quality: Make the logo clear, sharp, and professional

**Layout Guidance:**
- If multiple logos exist, arrange them in a clean, balanced way
- Maintain visual hierarchy - don't let logos compete for attention
- The new logo should establish brand identity without overwhelming the slide content or removing existing branding`;
    }

    // Build custom image instructions
    let customImageInstructions = '';
    if (params.customImage) {
      customImageInstructions = `

**CUSTOM IMAGE INSTRUCTION:** You have been provided with a custom image. Incorporate this image into the slide design in a visually appealing and professional manner that complements the overall layout.`;
    }

    // Build image parts array
    const imageParts: any[] = [];
    if (params.referenceSlideImage) {
      imageParts.push({ text: '--- REFERENCE SLIDE (FOR STYLE) ---' });
      imageParts.push(fileToGenerativePart(params.referenceSlideImage));
    }
    if (params.logoImage) {
      imageParts.push({ text: '--- COMPANY LOGO (ADD this while preserving existing logos) ---' });
      imageParts.push(fileToGenerativePart(params.logoImage));
    }
    if (params.customImage) {
      imageParts.push({ text: '--- CUSTOM IMAGE (TO INCLUDE) ---' });
      imageParts.push(fileToGenerativePart(params.customImage));
    }

    // Build designer system prompt
    const designerSystemPrompt = params.referenceSlideImage
      ? `You are a "Creative Slide Designer" AI. Your task is to create a brand new slide from scratch based on a detailed prompt.

**CRITICAL RULES:**
1.  **Reference Style:** You are provided with a reference slide image. The new slide you create MUST perfectly match the visual style, aesthetics, color palette, font choices, and general layout principles of this reference slide.
2.  **Follow Prompt:** Create the content of the new slide based *only* on the detailed prompt.
3.  **Aspect Ratio:** The new slide you create MUST be in a 16:9 aspect ratio.
---
**Detailed Prompt:** "${params.detailedPrompt}"${themeInstructions}${logoInstructions}${customImageInstructions}`
      : `You are a "Creative Slide Designer" AI. Your task is to create a brand new slide from scratch based on a detailed prompt.

**CRITICAL RULES:**
1. **Design Style:** Since no reference image is provided, create a clean, professional, and visually appealing design. Use a modern, minimalist aesthetic with good typography and layout principles.
2.  **Follow Prompt:** Create the content of the new slide based *only* on the detailed prompt.
3.  **Aspect Ratio:** The new slide you create MUST be in a 16:9 aspect ratio.
---
**Detailed Prompt:** "${params.detailedPrompt}"${themeInstructions}${logoInstructions}${customImageInstructions}`;

    // Generate the slide
    console.log(`[createSlideTool] Generating slide with Gemini 2.5 Flash Image...`);
    const result = await generateSingleImage(
      'gemini-2.5-flash-image',
      imageParts,
      designerSystemPrompt,
      params.deepMode
    );

    const executionTime = Date.now() - startTime;
    console.log(`[createSlideTool] ✅ Slide created in ${executionTime}ms`);

    return {
      success: true,
      data: {
        images: [result.image],
        prompts: [result.finalPrompt],
      },
      metadata: {
        executionTime,
        model: 'gemini-2.5-flash-image',
      },
    };
  } catch (error: any) {
    const executionTime = Date.now() - startTime;
    console.error(`[createSlideTool] ❌ Error:`, error);

    return {
      success: false,
      error: {
        code: 'SLIDE_CREATION_FAILED',
        message: 'Failed to create slide',
        details: error.message,
      },
      metadata: {
        executionTime,
      },
    };
  }
}

/**
 * ADK Tool Schema (to be exported by tools/index.ts)
 */
export const createSlideTool = {
  name: 'createSlideTool',
  description: 'Create a NEW slide from scratch based on a detailed prompt. Can include reference slides for style matching, brand themes, logos, and custom images.',
  parameters: {
    type: 'object',
    properties: {
      detailedPrompt: {
        type: 'string',
        description: 'Detailed description of the slide content and layout',
      },
      referenceSlideImage: {
        type: 'string',
        description: 'Optional: Base64 data URL of a reference slide to match visual style',
      },
      deepMode: {
        type: 'boolean',
        description: 'Enable deep thinking mode for better visual design (slower but higher quality)',
      },
      theme: {
        type: 'object',
        description: 'Optional: Brand theme with colors and typography',
        properties: {
          primaryColor: { type: 'string' },
          secondaryColor: { type: 'string' },
          accentColor: { type: 'string' },
          fontStyle: { type: 'string' },
          visualStyle: { type: 'string' },
          sources: { type: 'array', items: { type: 'string' } },
        },
      },
      logoImage: {
        type: 'string',
        description: 'Optional: Base64 data URL of company logo to include',
      },
      customImage: {
        type: 'string',
        description: 'Optional: Base64 data URL of a custom image to incorporate into the slide',
      },
    },
    required: ['detailedPrompt', 'deepMode'],
  },
  execute: createSlide,
};
