/**
 * minorEditSlideTool
 *
 * Makes MINOR edits to an existing slide using inpainting/masking
 *
 * Use cases:
 * - Change text in a specific region
 * - Modify colors or styling in a specific area
 * - Replace specific visual elements
 * - Fix typos or update data
 *
 * @tool
 */

import { GoogleGenAI } from '@google/genai';
import type { ToolResult, MinorEditSlideParams, MinorEditSlideResult } from '../types';

const ai = new GoogleGenAI({ apiKey: process.env.VITE_GEMINI_API_KEY || '' });

/**
 * Helper: Convert base64 data URL to GenerativePart
 */
function fileToGenerativePart(base64Data: string) {
  const match = base64Data.match(/^data:(image\/\w+);base64,(.*)$/);
  if (!match) {
    throw new Error('Invalid base64 image data string');
  }
  return {
    inlineData: {
      data: match[2],
      mimeType: match[1],
    },
  };
}

/**
 * Helper: Generate inpainted image using Gemini Flash Image
 */
async function generateInpaintedImage(
  originalImagePart: any,
  maskImagePart: any,
  prompt: string,
  deepMode: boolean
): Promise<{ image: string; finalPrompt: string }> {
  const parts = [
    originalImagePart,
    maskImagePart,
    { text: prompt },
  ];

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: [{ role: 'user', parts }],
    config: {
      thinking: deepMode
        ? { mode: 'deep', instruction: 'Think carefully about how to seamlessly integrate the edit into the existing slide design' }
        : undefined,
    },
  });

  // Find the image part (could be in any position in parts array)
  const responseParts = response?.candidates?.[0]?.content?.parts || [];
  let base64ImageBytes: string | undefined;
  let mimeType = 'image/png';

  for (const part of responseParts) {
    if (part.inlineData?.data) {
      base64ImageBytes = part.inlineData.data;
      mimeType = part.inlineData.mimeType || 'image/png';
      break;
    }
  }

  if (!base64ImageBytes) {
    throw new Error('No image was generated by Gemini (Reason: NO_IMAGE)');
  }
  return {
    image: `data:${mimeType};base64,${base64ImageBytes}`,
    finalPrompt: prompt,
  };
}

/**
 * Makes minor edits to an existing slide using inpainting
 * Wraps the tested getInpaintingVariations logic from services/geminiService.ts
 */
export async function minorEditSlide(params: MinorEditSlideParams): Promise<ToolResult<MinorEditSlideResult>> {
  const startTime = Date.now();

  try {
    console.log(`[minorEditSlideTool] Editing slide with instruction: ${params.prompt.substring(0, 100)}...`);
    console.log(`[minorEditSlideTool] Deep Mode: ${params.deepMode}`);

    // Prepare image parts
    const originalImagePart = fileToGenerativePart(params.base64Image);
    const maskImagePart = fileToGenerativePart(params.base64Mask);

    // Build inpainting prompt
    const inpaintingPrompt = `**Task: Inpainting**
Perform the following instruction ONLY within the masked area of the image. DO NOT change any pixels outside the masked area.

**Instruction:** "${params.prompt}"`;

    console.log(`[minorEditSlideTool] Generating inpainted image...`);

    // Generate inpainted variation
    const result = await generateInpaintedImage(
      originalImagePart,
      maskImagePart,
      inpaintingPrompt,
      params.deepMode
    );

    const executionTime = Date.now() - startTime;
    console.log(`[minorEditSlideTool] ✅ Inpainting complete in ${executionTime}ms`);

    return {
      success: true,
      data: {
        images: [result.image],
        variationPrompts: [result.finalPrompt],
      },
      metadata: {
        executionTime,
        model: 'gemini-2.5-flash-image',
      },
    };
  } catch (error: any) {
    const executionTime = Date.now() - startTime;
    console.error(`[minorEditSlideTool] ❌ Error:`, error);

    return {
      success: false,
      error: {
        code: 'INPAINTING_FAILED',
        message: 'Failed to perform inpainting on slide',
        details: error.message,
      },
      metadata: {
        executionTime,
      },
    };
  }
}

/**
 * ADK Tool Schema (to be exported by tools/index.ts)
 */
export const minorEditSlideTool = {
  name: 'minorEditSlideTool',
  description: 'Make MINOR edits to an existing slide using inpainting. Only the masked region will be modified. Use this for targeted changes like fixing typos, updating text, changing colors in a specific area, or replacing individual visual elements.',
  parameters: {
    type: 'object',
    properties: {
      prompt: {
        type: 'string',
        description: 'Edit instruction describing what to change in the masked area (e.g., "Change the text to say Welcome", "Make the background blue", "Replace the icon with a checkmark")',
      },
      base64Image: {
        type: 'string',
        description: 'Base64 data URL of the original slide image to edit',
      },
      base64Mask: {
        type: 'string',
        description: 'Base64 data URL of the mask image highlighting the area to edit (white = edit region, black = preserve region)',
      },
      deepMode: {
        type: 'boolean',
        description: 'Enable deep thinking mode for better quality edits (slower but more precise)',
      },
    },
    required: ['prompt', 'base64Image', 'base64Mask', 'deepMode'],
  },
  execute: minorEditSlide,
};
