/**
 * minorEditSlideTool
 *
 * Makes MINOR edits to an existing slide using inpainting/masking
 *
 * Use cases:
 * - Change text in a specific region
 * - Modify colors or styling in a specific area
 * - Replace specific visual elements
 * - Fix typos or update data
 *
 * @tool
 */

import { GoogleGenAI } from '@google/genai';
import type { ToolResult, MinorEditSlideParams, MinorEditSlideResult } from '../types';

const ai = new GoogleGenAI({ apiKey: process.env.VITE_GEMINI_API_KEY || '' });

/**
 * Helper: Convert base64 data URL to GenerativePart
 */
function fileToGenerativePart(base64Data: string) {
  const match = base64Data.match(/^data:(image\/\w+);base64,(.*)$/);
  if (!match) {
    throw new Error('Invalid base64 image data string');
  }
  return {
    inlineData: {
      data: match[2],
      mimeType: match[1],
    },
  };
}

/**
 * Helper: Generate inpainted image using Gemini Flash Image (with mask)
 */
async function generateInpaintedImage(
  originalImagePart: any,
  maskImagePart: any,
  prompt: string,
  deepMode: boolean
): Promise<{ image: string; finalPrompt: string }> {
  const parts = [
    originalImagePart,
    maskImagePart,
    { text: prompt },
  ];

  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-image-preview',
    contents: [{ role: 'user', parts }],
    config: {
      thinking: deepMode
        ? { mode: 'deep', instruction: 'Think carefully about how to seamlessly integrate the edit into the existing slide design' }
        : undefined,
    },
  });

  // Find the image part (could be in any position in parts array)
  const responseParts = response?.candidates?.[0]?.content?.parts || [];
  let base64ImageBytes: string | undefined;
  let mimeType = 'image/png';

  for (const part of responseParts) {
    if (part.inlineData?.data) {
      base64ImageBytes = part.inlineData.data;
      mimeType = part.inlineData.mimeType || 'image/png';
      break;
    }
  }

  if (!base64ImageBytes) {
    throw new Error('No image was generated by Gemini (Reason: NO_IMAGE)');
  }
  return {
    image: `data:${mimeType};base64,${base64ImageBytes}`,
    finalPrompt: prompt,
  };
}

/**
 * Helper: Generate edited image using Gemini Flash Image (without mask)
 */
async function generateEditedImage(
  originalImagePart: any,
  prompt: string,
  deepMode: boolean
): Promise<{ image: string; finalPrompt: string }> {
  const parts = [originalImagePart, { text: prompt }];

  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-image-preview',
    contents: [{ role: 'user', parts }],
    config: {
      thinking: deepMode
        ? { mode: 'deep', instruction: 'Think carefully about making minimal changes while preserving the slide design' }
        : undefined,
    },
  });

  // Find the image part (could be in any position in parts array)
  const responseParts = response?.candidates?.[0]?.content?.parts || [];
  let base64ImageBytes: string | undefined;
  let mimeType = 'image/png';

  for (const part of responseParts) {
    if (part.inlineData?.data) {
      base64ImageBytes = part.inlineData.data;
      mimeType = part.inlineData.mimeType || 'image/png';
      break;
    }
  }

  if (!base64ImageBytes) {
    throw new Error('No image was generated by Gemini (Reason: NO_IMAGE)');
  }

  return {
    image: `data:${mimeType};base64,${base64ImageBytes}`,
    finalPrompt: prompt,
  };
}

/**
 * Makes minor edits to an existing slide
 * Supports two modes:
 * 1. With mask: Inpainting (only edit masked region)
 * 2. Without mask: Instruction-based editing (e.g., "add logo to top right")
 *
 * Wraps the tested getInpaintingVariations logic from services/geminiService.ts
 */
export async function minorEditSlide(params: MinorEditSlideParams): Promise<ToolResult<MinorEditSlideResult>> {
  const startTime = Date.now();

  try {
    console.log(`[minorEditSlideTool] Editing slide with instruction: ${params.prompt.substring(0, 100)}...`);
    console.log(`[minorEditSlideTool] Mode: ${params.base64Mask ? 'Inpainting (with mask)' : 'Instruction-based (no mask)'}`);
    console.log(`[minorEditSlideTool] Deep Mode: ${params.deepMode}`);

    // Prepare image parts
    const originalImagePart = fileToGenerativePart(params.base64Image);

    let result;

    if (params.base64Mask) {
      // MODE 1: Inpainting with mask (only edit masked region)
      const maskImagePart = fileToGenerativePart(params.base64Mask);

      const inpaintingPrompt = `**Task: Inpainting**
Perform the following instruction ONLY within the masked area of the image. DO NOT change any pixels outside the masked area.

**Instruction:** "${params.prompt}"`;

      console.log(`[minorEditSlideTool] Generating inpainted image (masked region only)...`);

      result = await generateInpaintedImage(
        originalImagePart,
        maskImagePart,
        inpaintingPrompt,
        params.deepMode
      );
    } else {
      // MODE 2: Instruction-based editing (no mask)
      const editPrompt = `**Task: Minor Slide Edit**
Make the following MINOR edit to this slide. Keep the overall design, layout, and style the same. Only make the specific change requested.

**Edit Instruction:** "${params.prompt}"

**Important:** This is a MINOR edit, not a complete redesign. Preserve the existing slide's structure, colors, fonts, and layout as much as possible.`;

      console.log(`[minorEditSlideTool] Generating edited slide (instruction-based)...`);

      result = await generateEditedImage(
        originalImagePart,
        editPrompt,
        params.deepMode
      );
    }

    const executionTime = Date.now() - startTime;
    console.log(`[minorEditSlideTool] ✅ Inpainting complete in ${executionTime}ms`);

    return {
      success: true,
      data: {
        images: [result.image],
        variationPrompts: [result.finalPrompt],
      },
      metadata: {
        executionTime,
        model: 'gemini-3-pro-image-preview',
      },
    };
  } catch (error: any) {
    const executionTime = Date.now() - startTime;
    console.error(`[minorEditSlideTool] ❌ Error:`, error);

    return {
      success: false,
      error: {
        code: 'INPAINTING_FAILED',
        message: 'Failed to perform inpainting on slide',
        details: error.message,
      },
      metadata: {
        executionTime,
      },
    };
  }
}

/**
 * ADK Tool Schema (to be exported by tools/index.ts)
 */
export const minorEditSlideTool = {
  name: 'minorEditSlideTool',
  description: `Make MINOR edits to an existing slide. Supports TWO modes:

1. **Inpainting Mode (with mask)**: Edit only a specific region by providing a mask image. The mask highlights the area to modify (white = edit, black = preserve). Perfect for precise regional changes.

2. **Instruction Mode (without mask)**: Make small changes based on text instructions (e.g., "add logo to top right", "change date to November 2025"). The tool preserves the overall design while making the requested change.

Use cases:
- Add elements (logo, icon, text) to specific locations
- Change existing text or data
- Fix typos or update information
- Modify colors or styling in specific areas
- Replace individual visual elements

NOT for: Complete redesigns, major layout changes, or generating multiple variations (use redesignSlideTool instead).`,
  parameters: {
    type: 'object',
    properties: {
      prompt: {
        type: 'string',
        description: 'Edit instruction. Examples: "Add logo to top right corner", "Change Month 20XX to November 2025", "Make the background blue in this area", "Replace the icon with a checkmark"',
      },
      base64Image: {
        type: 'string',
        description: 'Base64 data URL of the original slide image to edit',
      },
      base64Mask: {
        type: 'string',
        description: 'OPTIONAL: Base64 data URL of the mask image (white = edit region, black = preserve region). If provided, only masked area is edited (inpainting mode). If not provided, entire slide can be edited based on instruction (instruction mode).',
      },
      deepMode: {
        type: 'boolean',
        description: 'Enable deep thinking mode for better quality edits (slower but more precise)',
      },
    },
    required: ['prompt', 'base64Image', 'deepMode'],
  },
  execute: minorEditSlide,
};
