/**
 * redesignSlideTool
 *
 * Completely REDESIGNS an existing slide based on new instructions
 *
 * Use cases:
 * - Change the overall layout or visual style
 * - Rewrite content while keeping the general message
 * - Apply a different design aesthetic
 * - Transform slide from one category to another
 *
 * Generates 3 variations to give users choice
 *
 * @tool
 */

import { GoogleGenAI } from '@google/genai';
import type { ToolResult, RedesignSlideParams, RedesignSlideResult } from '../types';

const ai = new GoogleGenAI({ apiKey: process.env.VITE_GEMINI_API_KEY || '' });

/**
 * Helper: Convert base64 data URL to GenerativePart
 */
function fileToGenerativePart(base64Data: string) {
  const match = base64Data.match(/^data:(image\/\w+);base64,(.*)$/);
  if (!match) {
    throw new Error('Invalid base64 image data string');
  }
  return {
    inlineData: {
      data: match[2],
      mimeType: match[1],
    },
  };
}

/**
 * Helper: Generate single redesigned variation
 */
async function generateRedesignedVariation(
  originalImagePart: any,
  systemPrompt: string,
  deepMode: boolean
): Promise<{ image: string; finalPrompt: string }> {
  const parts = [originalImagePart, { text: systemPrompt }];

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: [{ role: 'user', parts }],
    config: {
      thinking: deepMode
        ? { mode: 'deep', instruction: 'Think deeply about how to improve the slide design while maintaining the core message' }
        : undefined,
    },
  });

  // Find the image part (could be in any position in parts array)
  const responseParts = response?.candidates?.[0]?.content?.parts || [];
  let base64ImageBytes: string | undefined;
  let mimeType = 'image/png';

  for (const part of responseParts) {
    if (part.inlineData?.data) {
      base64ImageBytes = part.inlineData.data;
      mimeType = part.inlineData.mimeType || 'image/png';
      break;
    }
  }

  if (!base64ImageBytes) {
    throw new Error('No image was generated by Gemini (Reason: NO_IMAGE)');
  }
  return {
    image: `data:${mimeType};base64,${base64ImageBytes}`,
    finalPrompt: systemPrompt,
  };
}

/**
 * Redesigns an existing slide with 3 variations
 * Wraps the tested executeSlideTask logic from services/geminiService.ts
 */
export async function redesignSlide(params: RedesignSlideParams): Promise<ToolResult<RedesignSlideResult>> {
  const startTime = Date.now();

  try {
    console.log(`[redesignSlideTool] Redesigning slide with instruction: ${params.detailedPrompt.substring(0, 100)}...`);
    console.log(`[redesignSlideTool] Deep Mode: ${params.deepMode}`);

    // Prepare original image part
    const originalImagePart = fileToGenerativePart(params.base64Image);

    // Build artist system prompt
    const artistSystemPrompt = `You are a "Slide Redesign Artist" AI. Your task is to take the slide shown in the image and redesign it based on the user's request.

**Your Goal:** Create a NEW version of this slide that:
1. Implements the user's requested changes.
2. Maintains a 16:9 aspect ratio.
3. Keeps a professional, polished aesthetic.

**User's Redesign Request:** "${params.detailedPrompt}"

**Instructions:**
- Interpret the request and apply the changes to the slide's design, layout, or content.
- If the request is vague, make reasonable professional design choices.
- Ensure the redesigned slide is visually appealing and maintains readability.`;

    // Generate 3 variations for user choice
    const variationPrompts = [
      artistSystemPrompt,
      `${artistSystemPrompt}\n(For this version, interpret the request with a slightly more creative or visually distinct style.)`,
      `${artistSystemPrompt}\n(For this version, offer another clean and professional alternative.)`,
    ];

    console.log(`[redesignSlideTool] Generating 3 variations...`);

    // Generate all variations in parallel
    const promises = variationPrompts.map((prompt, idx) => {
      console.log(`[redesignSlideTool] Generating variation ${idx + 1}/3...`);
      return generateRedesignedVariation(originalImagePart, prompt, params.deepMode);
    });

    const settledResults = await Promise.allSettled(promises);

    // Collect successful results
    const images: string[] = [];
    const prompts: string[] = [];
    settledResults.forEach((result, idx) => {
      if (result.status === 'fulfilled') {
        images.push(result.value.image);
        prompts.push(result.value.finalPrompt);
        console.log(`[redesignSlideTool] ✅ Variation ${idx + 1} succeeded`);
      } else {
        console.error(`[redesignSlideTool] ❌ Variation ${idx + 1} failed:`, result.reason);
      }
    });

    if (images.length === 0) {
      throw new Error('All redesign variations failed to generate');
    }

    const executionTime = Date.now() - startTime;
    console.log(`[redesignSlideTool] ✅ Redesign complete in ${executionTime}ms (${images.length}/3 variations successful)`);

    return {
      success: true,
      data: {
        images,
        prompts,
      },
      metadata: {
        executionTime,
        model: 'gemini-2.5-flash-image',
      },
    };
  } catch (error: any) {
    const executionTime = Date.now() - startTime;
    console.error(`[redesignSlideTool] ❌ Error:`, error);

    return {
      success: false,
      error: {
        code: 'REDESIGN_FAILED',
        message: 'Failed to redesign slide',
        details: error.message,
      },
      metadata: {
        executionTime,
      },
    };
  }
}

/**
 * ADK Tool Schema (to be exported by tools/index.ts)
 */
export const redesignSlideTool = {
  name: 'redesignSlideTool',
  description: 'Completely REDESIGN an existing slide based on new instructions. Generates 3 different variations for the user to choose from. Use this for major changes to layout, style, or content structure.',
  parameters: {
    type: 'object',
    properties: {
      base64Image: {
        type: 'string',
        description: 'Base64 data URL of the slide to redesign',
      },
      detailedPrompt: {
        type: 'string',
        description: 'Detailed instructions for how to redesign the slide (e.g., "Make it more visual with icons", "Change to a dark theme", "Simplify the layout and reduce text")',
      },
      deepMode: {
        type: 'boolean',
        description: 'Enable deep thinking mode for better quality redesigns (slower but higher quality)',
      },
    },
    required: ['base64Image', 'detailedPrompt', 'deepMode'],
  },
  execute: redesignSlide,
};
