/**
 * Session Logger Service
 * Automatically saves debug sessions to log files for analysis
 */

import type { DebugSession, DebugLog } from '../types';

export type GenerationMode = 'designer' | 'smart-ai' | 'classic';

interface SessionLogMetadata {
  mode: GenerationMode;
  timestamp: string;
  duration?: number;
  slideCount: number;
  company?: string;
}

/**
 * Save session to downloadable file (browser-based)
 */
export function downloadSessionLog(session: DebugSession, metadata: SessionLogMetadata): void {
  const timestamp = new Date(session.timestamp).toISOString().replace(/[:.]/g, '-');
  const filename = `${metadata.mode}_${timestamp}_${metadata.slideCount}slides.md`;

  const markdown = formatSessionAsMarkdown(session, metadata);

  // Create blob and download
  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  console.log(`📥 Session log downloaded: ${filename}`);
}

/**
 * Save session to console in structured format
 */
export function logSessionToConsole(session: DebugSession, metadata: SessionLogMetadata): void {
  const separator = '='.repeat(80);

  console.log(`\n${separator}`);
  console.log(`📊 SESSION LOG - ${metadata.mode.toUpperCase()} MODE`);
  console.log(separator);
  console.log(`Timestamp: ${metadata.timestamp}`);
  console.log(`Company: ${metadata.company || 'Unknown'}`);
  console.log(`Slides: ${metadata.slideCount}`);
  console.log(`Duration: ${metadata.duration || 0}s`);
  console.log(`Status: ${session.status}`);
  console.log(`Model: ${session.model}`);
  console.log(separator);

  session.logs.forEach((log, idx) => {
    console.log(`\n[LOG ${idx + 1}/${session.logs.length}] ${log.title}`);
    console.log('-'.repeat(80));
    console.log(log.content.substring(0, 500) + (log.content.length > 500 ? '...' : ''));
  });

  console.log(`\n${separator}`);
  console.log(`📊 Full session object:`);
  console.log(session);
  console.log(separator);
}

/**
 * Automatically save session (downloads + console logs)
 */
export function autoSaveSession(session: DebugSession, metadata: SessionLogMetadata): void {
  // Log to console
  logSessionToConsole(session, metadata);

  // Auto-download log file
  downloadSessionLog(session, metadata);

  // Also save to localStorage for persistence
  saveToLocalStorage(session, metadata);
}

/**
 * Save to browser localStorage for session history
 */
function saveToLocalStorage(session: DebugSession, metadata: SessionLogMetadata): void {
  try {
    const key = `session_log_${metadata.mode}_${Date.now()}`;
    const data = {
      session,
      metadata
    };
    localStorage.setItem(key, JSON.stringify(data));
    console.log(`💾 Session saved to localStorage: ${key}`);
  } catch (e) {
    console.warn('Failed to save to localStorage:', e);
  }
}

/**
 * Format session as readable markdown
 */
function formatSessionAsMarkdown(session: DebugSession, metadata: SessionLogMetadata): string {
  let md = '';

  md += `# ${metadata.mode.toUpperCase()} MODE - Session Log\n\n`;
  md += `## Metadata\n\n`;
  md += `- **Timestamp:** ${metadata.timestamp}\n`;
  md += `- **Mode:** ${metadata.mode}\n`;
  md += `- **Company:** ${metadata.company || 'Unknown'}\n`;
  md += `- **Slides Generated:** ${metadata.slideCount}\n`;
  md += `- **Duration:** ${metadata.duration || 0}s\n`;
  md += `- **Status:** ${session.status}\n`;
  md += `- **Model:** ${session.model}\n`;
  md += `- **Deep Mode:** ${session.deepMode ? 'Yes' : 'No'}\n\n`;

  md += `---\n\n`;
  md += `## Initial Prompt\n\n`;
  md += `\`\`\`\n${session.initialPrompt}\n\`\`\`\n\n`;

  md += `---\n\n`;
  md += `## Generation Logs\n\n`;

  session.logs.forEach((log, idx) => {
    md += `### ${idx + 1}. ${log.title}\n\n`;

    // Try to format as code block if it looks like JSON or code
    if (log.content.includes('{') || log.content.includes('```')) {
      md += `\`\`\`\n${log.content}\n\`\`\`\n\n`;
    } else {
      md += `${log.content}\n\n`;
    }

    md += `---\n\n`;
  });

  md += `## Final Output\n\n`;
  md += `- **Total Images Generated:** ${session.finalImages.length}\n`;
  md += `- **Workflow:** ${session.workflow}\n\n`;

  if (session.error) {
    md += `## Error\n\n`;
    md += `\`\`\`\n${session.error}\n\`\`\`\n\n`;
  }

  md += `---\n\n`;
  md += `*Generated by Deckr.ai Session Logger at ${new Date().toISOString()}*\n`;

  return md;
}

/**
 * Get all sessions from localStorage
 */
export function getAllSessions(mode?: GenerationMode): Array<{ session: DebugSession; metadata: SessionLogMetadata }> {
  const sessions: Array<{ session: DebugSession; metadata: SessionLogMetadata }> = [];

  for (let i = 0; i < localStorage.length; i++) {
    const key = localStorage.key(i);
    if (key && key.startsWith('session_log_')) {
      if (mode && !key.includes(mode)) continue;

      try {
        const data = JSON.parse(localStorage.getItem(key) || '{}');
        sessions.push(data);
      } catch (e) {
        console.warn(`Failed to parse session ${key}:`, e);
      }
    }
  }

  return sessions.sort((a, b) =>
    new Date(b.metadata.timestamp).getTime() - new Date(a.metadata.timestamp).getTime()
  );
}

/**
 * Clear all stored sessions
 */
export function clearAllSessions(): void {
  const keys: string[] = [];
  for (let i = 0; i < localStorage.length; i++) {
    const key = localStorage.key(i);
    if (key && key.startsWith('session_log_')) {
      keys.push(key);
    }
  }
  keys.forEach(key => localStorage.removeItem(key));
  console.log(`🗑️ Cleared ${keys.length} session logs`);
}
